from typing import List, Dict, Any

class DataStorageInterface:
    def get_performance_all(self) -> List[Dict[str, Any]]:
        ...

    def get_performance_by_opids(self, opids: List[int]) -> List[Dict[str, Any]]:
        ...

    def get_latest_perf_data_date(self) -> str:
        ...

    def get_subscriptions_by_type(self, sub_type: str) -> Dict[str, Any]:
        ...

    def get_subscriptions_by_userid(self, user_id: int) -> Dict[str, Any]:
        ...

    def add_user_subscription(self, user_id: int, op_id: int, sub_type: str, sub_data: Any) -> Dict[str, Any]:
        ...

    def del_user_subscription(self, user_id: int, op_id: int, sub_type: str) -> Dict[str, Any]:
        ...