MAX_DISCORD_MESSAGE_LENGTH = 1800

DYNDB_SUB_TABLE = 'SSVPerformanceSubscriptions'

OPERATOR_24H_HISTORY_COUNT = 7

FIELD_OPERATOR_ID = 'OperatorID'
FIELD_OPERATOR_NAME = 'Name'
FIELD_IS_VO = 'isVO'
FIELD_VALIDATOR_COUNT = 'ValidatorCount'
FIELD_ADDRESS = 'Address'
FIELD_PERF_DATA_1H = 'Performance1h'
FIELD_PERF_DATA_24H = 'Performance24h'
FIELD_PERF_DATA_30D = 'Performance30d'
FIELD_PERF_DATA_90D = 'Performance90d'

ALERTS_THRESHOLDS_24H = {0.95, 0.75}
ALERTS_THRESHOLDS_30D = {0.95}